In [10]:
import pandas as pd
import numpy as np
from scipy import stats
import plotly.express as px

In [14]:
from utils import csv_downloader

In [16]:
df = csv_downloader(
    "https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/cohort/cohort_analysis.csv",
    "cohort_analysis1",
    "../data/processed"
    )

cohort_analysis1 saved in ../data/processed | shape: (12000, 12)

In [17]:
df.head()

,user_id,acquisition_date,cancellation_month,gender,marital_status,age,income_segment,country,channel,campaign_id,device_type,plan_type
0,1,2024-07-01,2025-03-01,Male,Married,31,Medium,Germany,Paid Ads,Paid Ads_C,iOS,Standard
1,2,2024-04-01,2024-09-01,Male,Single,54,Premium,Netherlands,Referral,Referral_B,iOS,Standard
2,3,2024-05-01,NaN,Male,Single,34,Medium,Poland,Paid Ads,Paid Ads_A,Android,Standard
3,4,2024-07-01,NaN,Male,Married,38,High,Belgium,Organic,Organic_C,Android,Standard
4,5,2024-03-01,2024-04-01,Male,Single,25,Low,Sweden,Paid Ads,Paid Ads_A,Android,Basic

In [18]:
df.shape

(12000, 12)

In [19]:
df.isna().sum()

user_id                  0
acquisition_date         0
cancellation_month    3581
gender                   0
marital_status           0
age                      0
income_segment         631
country                  0
channel                  0
campaign_id              0
device_type              0
plan_type                0
dtype: int64

In [21]:
df.describe()

           user_id           age
count  12000.00000  12000.000000
mean    6000.50000     34.630250
std     3464.24595      9.514896
min        1.00000     18.000000
25%     3000.75000     28.000000
50%     6000.50000     34.000000
75%     9000.25000     41.000000
max    12000.00000     65.000000